### ISSUE TITLE
Support for non-WOFF source fonts

### ISSUE THREAD

**Issue by pepelsbey** [sapegin/fontoptim#2]
I would be great to use TTF or OTF files as a source for resulted WOFF inline fonts. I would make this tool even better as it won’t require extra Font Squirrel step.

**Comment by sapegin** [comment]
I thinks it’s better to use [ttf2woff](https://github.com/fontello/ttf2woff) to generate WOFF files (there are Grunt and Gulp plugins). But the real problem is WOFF2: the only available tool is Google’s [woff2](https://github.com/google/woff2) which you have to compile and which most probably won’t work on Windows.
